### ISSUE TITLE
Module depends on role IIS-WebServerRole to be enabled

### ISSUE THREAD

**Issue by timidri** [opentable/puppet-iis#47]
After installing opentable-iis with dependencies on a vanilla Windows 2012 R2 server, I got:

`Import-Module : The specified module 'WebAdministration' was not loaded because no valid module file was found in any module directory.`

I needed to do 

```puppet
dism { 'IIS-WebServerRole':
     ensure => present,
   }
```
to be able to use the module.

Is it an idea to either document or enforce this?

**Comment by liamjbennett** [comment]
I expect that this issue will be resolved by this PR: #26
